/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-container": "#fec931",
        "surface-container": "#111827",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#001f24",
        "on-secondary": "#1000a9",
        "surface-dim": "#0a0e17",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#9ca3af",
        "on-tertiary": "#3e2e00",
        "background": "#0b0f19",
        "surface-bright": "#1f2937",
        "surface-container-low": "#0e1320",
        "growth-green": "#10b981",
        "surface-container-highest": "#374151",
        "surface-variant": "#1f2937",
        "on-error": "#690005",
        "on-tertiary-fixed": "#251a00",
        "surface-black": "#070a13",
        "on-primary": "#00363d",
        "inverse-primary": "#006875",
        "secondary-container": "#1f2937",
        "border-gray": "#1f2937",
        "error": "#f87171",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#dbeafe",
        "on-background": "#f3f4f6",
        "inverse-surface": "#f3f4f6",
        "deep-indigo": "#060b18",
        "primary-fixed": "#3b82f6",
        "surface-container-high": "#1f2937",
        "primary": "#3b82f6",
        "secondary": "#6366f1",
        "primary-fixed-dim": "#60a5fa",
        "inverse-on-surface": "#1f2937",
        "surface-container-lowest": "#05070e",
        "outline-variant": "#374151",
        "surface-tint": "#60a5fa",
        "surface": "#0b0f19",
        "error-container": "#7f1d1d",
        "secondary-fixed-dim": "#a5b4fc",
        "on-secondary-container": "#c7d2fe",
        "secondary-fixed": "#e0e7ff",
        "on-tertiary-fixed-variant": "#594400",
        "technical-gray": "#111827",
        "tertiary": "#ffeac0",
        "tertiary-fixed": "#ffdf96",
        "on-secondary-fixed": "#07006c",
        "on-primary-fixed-variant": "#004f58",
        "outline": "#6b7280",
        "on-tertiary-container": "#6f5500",
        "on-surface": "#f3f4f6",
        "tertiary-fixed-dim": "#f3bf26"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.375rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "1.5rem",
        "margin-mobile": "1.5rem",
        "stack-sm": "0.5rem",
        "section-gap": "8rem",
        "margin-desktop": "5rem",
        "stack-md": "1rem"
      },
      "fontFamily": {
        "code-sm": ["Inter"],
        "label-caps": ["Poppins"],
        "display-xl": ["Poppins"],
        "headline-lg": ["Poppins"],
        "headline-md": ["Poppins"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "code-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.15em", "fontWeight": "600" }],
        "display-xl": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "display-xl-mobile": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
